# Generated by Django 4.0 on 2023-08-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_completed_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='right_answers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completed',
            name='wrong_answers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
